### PR TITLE
Fix a number of deprecation warnings

### PR DESCRIPTION
**Pull request by erikd**
The GTK developers seem to have an immense hatred of developers.
They deprecate functions at the drop of a hat and often provide
zero documentation on what to do to replace the now deprecated
functionality.

Started work on removing deprecation warnings. These are the easy ones. I don't think I've broken anything but would appreciate feedback if I've got anything wrong.

### CODE REVIEW

**Review by jplatte — APPROVED** [review]
From the PR description I first thought you disabled deprecation warnings via an overrides file and was going to complain :D

Looks good to me.

**Comment by erikd** [comment]
Disabling warnings /= fixing warnings :).

**Comment by jplatte** [comment]
Well yeah, the title says that. But in the description you rant about the gtk devs and talk about "removing deprecation warnings". That's why I was confused.

**Comment by erikd** [comment]
Thanks @hamishmack !

**Comment by hamishmack** [comment]
Thanks for fixing these.  It is cool that haskell-gi alerts us about these and it will always include the new functions we need to use (even if they are not document well).  I dread to think the amount of technical debt Gtk2Hs will have accumulated by the time Gtk+ 4 comes out.  The port of Gtk2Hs itself from Gtk+ 2 to Gtk+ 3 is still only half done (missing lots of Gtk+ 3 functions)!

**Comment by erikd** [comment]
I'm still trying to fix the rest, but some of them are really difficult. For instance, in the carsim example has
```
        al <- alignmentNew 0.5 0.5 0 1
        alignmentSetPadding al 15 15 15 15
        containerAdd al sc
        return al
```
but `gtk_alignment_new` is deprecated and the upstream GTK documentation suggests using "GtkWidget alignment and margin properties" for which I cannot find any information.

**Comment by jplatte** [comment]
Hm, what about these:

* https://developer.gnome.org/gtk3/unstable/GtkWidget.html#GtkWidget--margin
* https://developer.gnome.org/gtk3/unstable/GtkWidget.html#GtkWidget--halign
* https://developer.gnome.org/gtk3/unstable/GtkWidget.html#GtkWidget--valign

or the corresponding setters:

* https://developer.gnome.org/gtk3/unstable/GtkWidget.html#gtk-widget-set-margin-start (I guess there is no setter for the "all margins" property..)
* https://developer.gnome.org/gtk3/unstable/GtkWidget.html#gtk-widget-set-halign
* https://developer.gnome.org/gtk3/unstable/GtkWidget.html#gtk-widget-set-valign

**Comment by erikd** [comment]
I did find the first set but could not figure out how to set them from haskell code. I ended up making four calls, one to each of `widgetSetMarginStart` `widgetSetMarginEnd`, `widgetSetMarginTop` and `widgetSetMarginBottom`.

**Comment by jplatte** [comment]
There are `get` and `set` functions for GObject properties (they are found in `Data.GI.Base`). They rely on GHC 8's OverloadedLabels extension so I'm not sure if it would be a good idea to use them here. There's also another way that involves generating a big file that contains all these properties that I've already mostly forgotten how to do, and might or might not still be supported (ping @garetxe).

The [README.md](https://github.com/haskell-gi/haskell-gi#haskell-gi) of the main repo has a code example that uses OverloadedLabels and the `set` function.

**Comment by hamishmack** [comment]
`widgetSetMarginStart` corresponds to `gtk_widget_set_margin_start` not all Gtk+ properties have a setter function like this.  So for some properties you will need to use the `setWidgetMarginStart` version instead (it calls the Gtk+ property functions instead).

I am not a fan of `set`, `:=` and OverloadedLabels.  If you want something similar without them you could use something like:

```Haskell
mapM_ ($al) [ (`widgetSetMarginStart` 1)
            , (`widgetSetMarginEnd` 1)
            , (`widgetSetMarginTop` 1)
            , (`widgetSetMarginBottom` 1)
            ]
```

But calling the set functions directly seems more readable to me.

**Pull request merged**
